name: stock_forecast
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - plotly=5.22.0
  - scikit-learn=1.4.2
  - statsmodels=0.14.1
  - scipy=1.13.1
  - jupyterlab=4.2.1
  - ipykernel=6.29.4
  - pip
  - pip:
      - yfinance==0.2.38
      - tensorflow==2.16.1
      - keras==2.16.0
      - streamlit==1.35.0
