name: stock-forecasting-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - statsmodels=0.14.2
  - prophet=1.1.5
  - cmdstanpy=1.2.0
  - plotly=5.21.0
  - openpyxl=3.1.2
  - pyarrow=15.0.2
  - jupyterlab=4.1.5
  - ipykernel=6.29.4
  - streamlit=1.35.0
  - pip
  - pip:
      - tensorflow==2.16.1
      - keras==3.3.3
