name: Daily Data Update

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libfreetype6-dev libpng-dev libopenblas-dev liblapack-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run data loader and batch runner
        run: python src/data_loader.py

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data_loader_log
          path: data_loader.log